refactor: rebrand to web3auth
torusresearch/openlogin-swift-sdk pull request #13
Opened 2022-03-14 08:00 UTC by michaellee8

2022-03-14 09:33 UTC, tanujgupta approved these changes

2022-03-14 11:59 UTC, chaitanyapotti requested changes
pls change the url

2022-03-14 11:59 UTC, chaitanyapotti commented on Web3Auth.podspec
> +  spec.source        = { :git => "https://github.com/torusresearch/web3auth-swift-sdk.git", :tag => spec.version }
this would change to https://github.com/web3auth/web3auth-swift-sdk
Pls replace this everywhere

2022-03-14 11:59 UTC, chaitanyapotti commented
Also, release and update the version of fetch-node-details package

2022-03-18 20:15 UTC, chaitanyapotti approved these changes
lgtm

2022-03-18 20:15 UTC, merged